name: docs-ci

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "main" ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Markdownlint
        run: npm run mlint

      - name: Spell check (cspell)
        run: npm run spell
